version: '3.7'

services:
  odoo:
    image: odoo:12.0
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 8069:8069/tcp
    env_file: 
        - .env
        - ../global.env    
    hostname: liofal.synology.me
    logging:
      driver: json-file
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      odoo:
    volumes:
      - odoo-web-data:/var/lib/odoo

  db:
    image: postgres:10
    restart: unless-stopped
    env_file: 
        - .env
        - ../global.env    
    hostname: liofal.synology.me
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
       - odoo-db-data:/data/postgres
    logging:
      driver: json-file
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      odoo:

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - odoo-pgadmin-data:/root/.pgadmin
    ports:
      - 5050:80/tcp
    logging:
      driver: json-file
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      odoo:
  
volumes:
  odoo-web-data:
  odoo-db-data:
  odoo-pgadmin-data:

networks:
  odoo:
    name: odoo  

