version: '3.7'

services:

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file

volumes:
  portainer_data:
