version: '3.7'

services:
  ubooquity:
    image: linuxserver/ubooquity:latest
    restart: unless-stopped
    ports:
      - 2202:2202/tcp
      - 2203:2203/tcp
    env_file: 
        - .env
        - ../global.env    
    hostname: liofal.synology.me
    volumes:
      - /volume1/docker/ubooquity/config:/config
      - /volume1/comics:/comics
    logging:
      driver: json-file
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      ubooquity:
  
networks:
  ubooquity:
    name: ubooquity
  